### ISSUE TITLE
Result not accurate 

### ISSUE THREAD

**Issue by IRSHAD500THUKROO** [murtazav/Audio-Classification-of-Indian-Languages#1]
i tried to run the code but i get only tamil results , bengal and marathi does not get included .
As in code we fetch the tamil data only , how to include bengali and marathi

Thanks in advance

**Comment by murtazav** [comment]
in the notebook, in the 6th code block, change the "path" to the folder containing these folders https://drive.google.com/drive/folders/1VgWMfKCoivWmQ_HwhnRnTlZDWw1FV-j3
These are mel-spectrogram images. If you directly use these images no need to execute the 4th and 5th blocks. The 4th and 5th block of code is to show how to convert audio to mel-spectrograms. (the code has shown the conversion only for Tamil). Please change "Tamil" to "Bengali or "Marathi" in path strings in those code blocks to get correct spectrograms in the right folders.
If you have many languages consider wrapping one more for loop around the 4th code block.

**Comment by IRSHAD500THUKROO** [comment]
Thanks  a lot sir it means a lot to me, Do u have any paper related to it,
I want to understand the working,  could u please suggest me a source. I am
trying to work on Kashmiri language will this model work on Kashmiri
language

Regards
Irshad

**Comment by murtazav** [comment]
Please contact via mail: mhv11@iitbbs.ac.in for further details.
